### ISSUE TITLE
作者你還好嗎？

### ISSUE THREAD

**Issue by CN-make** [xisuo67/XHS-Spider#100]
![image](https://github.com/xisuo67/XHS-Spider/assets/135316273/ccac3e24-e6e0-4999-ba01-85a61092dea8)
這個檢測系統出現什麼問題了嗎？ 如圖所示顯示接口關閉

**Comment by xisuo67** [comment]
你被墙了吧？刚检测服务是正常的，能正常检测授权

**Comment by CN-make** [comment]
> 你被墙了吧？刚检测服务是正常的，能正常检测授权

尊嘟假嘟 你把我牆了嗎？

**Comment by xisuo67** [comment]
你是台湾的？
