### ISSUE TITLE
下載功能接口出現異常

### ISSUE THREAD

**Issue by CN-make** [xisuo67/XHS-Spider#102]
![image](https://github.com/xisuo67/XHS-Spider/assets/135316273/2686e21a-e8cc-4743-815b-1cedc18cbcdc)
 版本號v1.019 
 還是下載圖片失敗
 更換版本 
 重新啟動軟體
 重新啟動設備
 均如圖片上所 顯示 但是視頻發佈出去又可以正常顯示出來

**Comment by CN-make** [comment]
但是視頻藉口雖然不顯示預覽 但是發佈出去還是正常可以播放的

**Comment by xisuo67** [comment]
目前陆续收到相同反馈，关于图片下载无法预览问题
最近没有太多时间来排查这个问题，该问题会在2.0版本得到修复
如果影响你们使用，可以暂时更换别的采集软件

**Comment by CN-make** [comment]
> 目前陆续收到相同反馈，关于图片下载无法预览问题 最近没有太多时间来排查这个问题，该问题会在2.0版本得到修复 如果影响你们使用，可以暂时更换别的采集软件

沒事 可能是人群太多了 但是不是無法預覽是圖片丟失的問題啦 只是幫助反饋 沒有催修復的意思 希望恢復這個贊助二維碼

**Comment by xisuo67** [comment]
重新下载1.9版本，解决了单条笔记采集失败
