### ISSUE TITLE
2.0版本增加设置-避免自动获取复制的链接后会造成解析或下载时的问题

### ISSUE THREAD

**Issue by xisuo67** [xisuo67/XHS-Spider#103]
### Discussed in https://github.com/xisuo67/XHS-Spider/discussions/84

<div type='discussions-op-text'>

<sup>Originally posted by **canyuehen** June 28, 2023</sup>
不知道大家有没有这个问题，
1、我复制了主页链接进行解析，最小化了软件。
2、在解析过程中我看到了一个视频，就复制了链接用小程序下载，但是软件就会自动获取复制的链接并且确认，之前解析了的就会消失，要重新操作第一步。
整体来说就是在解析和下载过程中不能复制链接</div>

**Comment by CN-make** [comment]
有的時候會監聽我的剪切板 然後自動跳轉剪切板的鏈接 但是沒有出現跳轉後出現自動下載的功能

**Comment by xisuo67** [comment]
增加参数配置，允许关闭剪切板监听事件

**Comment by xisuo67** [comment]
随2.0一起发布
