### ISSUE TITLE
去水印是否还正常？

### ISSUE THREAD

**Issue by TimeLessLing** [xisuo67/XHS-Spider#104]
请教一下作者大大，小红书于昨日更新了代码，所有的traceId都变成了空，之前主流的去水印思路是通过traceId构造无水印的图像链接，请问XHS-Spider在这次更新后还能爬取到无水印图片吗？

**Comment by xisuo67** [comment]
1.9版本已修复这个问题，不过已经不能像原来一样拿到原图了！采集单条笔记那里忘记修复，后面会在2.0版本一起修复掉这个问题
