### ISSUE TITLE
搜索框输入URL的识别BUG

### ISSUE THREAD

**Issue by Coobex** [xisuo67/XHS-Spider#109]
在搜索界面时可以正常识别url地址是单条笔记还是博主首页地址，但在已搜索出结果的页面内重新输入URL搜索，就不再识别，都按上一次搜索的URL类型匹配，如第一次使用单条笔记URL搜索，此时再输入博主首页地址，就会报错，提示当前URL不符合所属模块搜索要求。
出现问题版本好：1.0.1.9

**Comment by xisuo67** [comment]
已收到bug返回，复现后会尽快修复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月15日(周五) 晚上9:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xisuo67/XHS-Spider] 搜索框输入URL的识别BUG (Issue #109)




 
在搜索界面时可以正常识别url地址是单条笔记还是博主首页地址，但在已搜索出结果的页面内重新输入URL搜索，就不再识别，都按上一次搜索的URL类型匹配，如第一次使用单条笔记URL搜索，此时再输入博主首页地址，就会报错，提示当前URL不符合所属模块搜索要求。
 出现问题版本好：1.0.1.9

**Comment by xisuo67** [comment]
> 在搜索界面时可以正常识别url地址是单条笔记还是博主首页地址，但在已搜索出结果的页面内重新输入URL搜索，就不再识别，都按上一次搜索的URL类型匹配，如第一次使用单条笔记URL搜索，此时再输入博主首页地址，就会报错，提示当前URL不符合所属模块搜索要求。 出现问题版本好：1.0.1.9

之前开发的时候考虑博主首页只识别博主首页链接，单条笔记仅识别单条笔记链接，导致目前情况出现！如果想在单条/博主搜索页面快速来回切换，可考虑使用Ctrl+C两次，切换到不同的页面

2.0将考虑增加博主及单条采集页面来回切换功能

**Comment by xisuo67** [comment]
已优化、增加功能，允许单条笔记、博主搜索页面来回切换
随2.0版本一起发布
