### ISSUE TITLE
视频解析下载乱码

### ISSUE THREAD

**Issue by luanshils** [xisuo67/XHS-Spider#111]
音频正常，但是图像不正常

**Comment by xisuo67** [comment]
将你采集链接发出来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月21日(周四) 下午4:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xisuo67/XHS-Spider] 视频解析下载乱码 (Issue #111)




 
音频正常，但是图像不正常

**Comment by xisuo67** [comment]
长时间无回复，关闭该issues
