### ISSUE TITLE
批量下载文件夹为空

### ISSUE THREAD

**Issue by bb67ao** [xisuo67/XHS-Spider#112]
下载某一博主下面所有内容的时候，只生成了文件夹，没有图片，偶尔有几个文件夹有视频文件，一共大概2000+文件夹，不知道什么原因

**Comment by xisuo67** [comment]
采集链接发出来

**Comment by bb67ao** [comment]
https://www.xiaohongshu.com/user/profile/5acc8ef44eacab21c39c0615?xhsshare=CopyLink&appuid=5d20929b0000000012000a20&apptime=1695183724

**Comment by bb67ao** [comment]
> 采集链接发出来

佬，这个是出于什么问题呢，有没有什么解决方案

**Comment by xisuo67** [comment]
> > 采集链接发出来
> 
> 佬，这个是出于什么问题呢，有没有什么解决方案

周末还没空看，最近比较忙，不过你采集连接，不要带
![image](https://github.com/xisuo67/XHS-Spider/assets/22284363/d36a6da5-7c3b-43dc-9016-392e16cce62a)
这些内容

**Comment by bb67ao** [comment]
okk，我再试试

**Comment by bb67ao** [comment]
> > > 采集链接发出来
> > 
> > 
> > 佬，这个是出于什么问题呢，有没有什么解决方案
> 
> 周末还没空看，最近比较忙，不过你采集连接，不要带 ![image](https://user-images.githubusercontent.com/22284363/270210577-d36a6da5-7c3b-43dc-9016-392e16cce62a.png) 这些内容

这个改了之后还是不行

**Comment by xisuo67** [comment]
你用的是什么版本？

**Comment by bb67ao** [comment]
> 你用的是什么版本？

[v1.0.1.9](https://github.com/xisuo67/XHS-Spider/releases/tag/v1.0.1.9)

**Comment by xisuo67** [comment]
这个issues关闭了

**Comment by bb67ao** [comment]
> ![image](https://user-images.githubusercontent.com/22284363/270287256-e1cfb7ad-b53c-4287-bfa2-3ea72531bb38.png) 等2.0版本或重新下载1.9版本，我没复现你的问题 2.0版本将恢复原图下载，预计十一以后发布，你可以再等等

需要在全部解析并下载的情况下出现这种问题，这个博主下笔记一共两千多篇，在少量批下载时候，我这边也没什么问题
