### ISSUE TITLE
所有的图片都是 12k 的 .png 格式，损坏了无法打开。

### ISSUE THREAD

**Issue by mikiU2022** [xisuo67/XHS-Spider#113]
![IMAGE 2023-09-24 18:06:59](https://github.com/xisuo67/XHS-Spider/assets/101374200/0be38da4-bed9-46c9-9563-0a8cec2b4f2f)

**Comment by xisuo67** [comment]
版本号，采集地址，复现步骤

**Comment by xisuo67** [comment]
重新下载1.9版本！
