### ISSUE TITLE
批量下载博主的多条笔记时，下载进程会不明原因停止，查询下载进度为剩余0。

### ISSUE THREAD

**Issue by guyuanqingxiang** [xisuo67/XHS-Spider#114]
### Version

1.0.1.9

### Platform

win11

### Steps to reproduce

采集链接：
https://www.xiaohongshu.com/user/profile/5dba3ea00000000001000093?xhsshare=CopyLink&appuid=59b3ca226a6a6943fea9e8c4&apptime=1696275071

### Details

博主全部笔记为157条，解析完成并点击全部下载后，下面小窗会跳下载进度提示，一开始会看到数字在跳，后面就不跳了，点击下载进度，显示剩余【0】文件待下载，但是文件夹并没有下载到全部内容。

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [X] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [ ] 我赞助了这个项目

**Comment by xisuo67** [comment]
补充系统设置页面截图

**Comment by xisuo67** [comment]
2.0版本观察一下是否还有这个问题，如果有，再打开这个问题
