### ISSUE TITLE
现在全选的逻辑是，全选vs反选，可不可以有一个全选vs取消全选的选项？

### ISSUE THREAD

**Issue by guyuanqingxiang** [xisuo67/XHS-Spider#115]
总共有5个笔记，
先选中其中2个，然后勾左上角的全选方框，这时候选中的是另外3个，也就是说变成了反选。
一般的全选勾上应该是选中所有笔记（5条），勾掉就是取消全选（0条），希望实现这个效果。

<img width="272" alt="image" src="https://github.com/xisuo67/XHS-Spider/assets/74532724/4bd4f247-b82e-468f-aec6-acbbc378e32c">
<img width="283" alt="image" src="https://github.com/xisuo67/XHS-Spider/assets/74532724/b6780709-0bb7-4661-a073-53ccd62e9970">

**Comment by xisuo67** [comment]
目前程序逻辑，有勾选项解析勾选项，无勾选项解析全部，下载逻辑也是这样
这里勾选根本的作用其实是为了解决部分用户只想采集部分数据，如果需要全部解析或下载，不要勾选任何选项就行了
