### ISSUE TITLE
能否按笔记类型进行筛选？

### ISSUE THREAD

**Issue by guyuanqingxiang** [xisuo67/XHS-Spider#116]
现在的笔记类型显示为“视频”or“图文”，想要可以按照笔记类型筛选，筛出来的内容为only视频或only图文。

**Comment by guyuanqingxiang** [comment]
另外看到作者有在其他issue回复“别的版本已实现导出excel功能，不在这个版本发布”，能否告知下是哪个版本，多谢！

**Comment by xisuo67** [comment]
> 现在的笔记类型显示为“视频”or“图文”，想要可以按照笔记类型筛选，筛出来的内容为only视频或only图文。

有排序功能，不考虑做筛选，界面上没位置放了

**Comment by xisuo67** [comment]
> 另外看到作者有在其他issue回复“别的版本已实现导出excel功能，不在这个版本发布”，能否告知下是哪个版本，多谢！

后面考虑将导入功能合并到主干，未来两个版本之内增加这个功能，不用着急
