### ISSUE TITLE
请问是否可以添加按点赞数量排名帖子的功能？

### ISSUE THREAD

**Issue by aquamarinz** [xisuo67/XHS-Spider#117]
目前点击<点赞数量>并不会将可下载帖子按点赞量排名，请问未来是否可以添加此功能？

**Comment by xisuo67** [comment]
![image](https://github.com/xisuo67/XHS-Spider/assets/22284363/e7fd3415-763e-4101-be65-c006cf271556)
目前程序支持点赞排序功能！扫码登陆后，自行点击点赞数量，是支持排序功能的，如果没有扫码登录，拿不到点赞具体数量，无法排序
