### ISSUE TITLE
能否添加分类下载的功能

### ISSUE THREAD

**Issue by S-fenghuayun** [xisuo67/XHS-Spider#118]
笔记超过1000很容易出错。
比方笔记有1000多条，其中600多是视频，我不想要视频，因为全部解析后下载出来的只有视频，图片文件夹是空的，并且视频也不全。
目前只有全选，全选是包括所有类别的。
可不可以选择一个类别显示，其他类别隐藏，这样对于笔记数很多的情况，不容易出现BUG，并且可以更加容易挑选下载。

**Comment by xisuo67** [comment]
已开发完成，2.3版本将集成该功能
