### ISSUE TITLE
Win10专业版在打开下载完成提示的情况下不提示下载完成，点击进度查询无反应

### ISSUE THREAD

**Issue by wangjigen** [xisuo67/XHS-Spider#119]
### Version

v1.0.1.9

### Platform

win10

### Steps to reproduce

![image](https://github.com/xisuo67/XHS-Spider/assets/48021722/0af7ca30-2567-41ff-b842-73a26786b8e4)

### Details

点击查询下载进度后显示下载进度但无任何反应
下载完成后也无任何提示只是默默下载

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [X] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [ ] 我赞助了这个项目

**Comment by xisuo67** [comment]
检查是否关闭了windows提示
![image](https://github.com/xisuo67/XHS-Spider/assets/22284363/60b35882-0390-453e-aaec-0026698dfce2)
