### ISSUE TITLE
下载的图片都是“lisa银发灰色”

### ISSUE THREAD

**Issue by Pangweiyun** [xisuo67/XHS-Spider#121]
### Version

2.1

### Platform

windows 10

### Steps to reproduce

https://www.xiaohongshu.com/explore/645e0323000000001300da4c

### Details

比如https://www.xiaohongshu.com/explore/645e0323000000001300da4c这个链接，QQ群里面也有好几个人提到了这个问题

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [X] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [ ] 我赞助了这个项目

**Comment by xisuo67** [comment]
2.2版本修复这个问题
