### ISSUE TITLE
解析失败

### ISSUE THREAD

**Issue by Lesliexi233** [xisuo67/XHS-Spider#122]
### Version

v1.0.2.1

### Platform

Windows 10

### Steps to reproduce

![解析失败](https://github.com/xisuo67/XHS-Spider/assets/148743326/fbad8d5c-61cc-465b-8a47-8cb691f6e1f4)
![解析主页失败](https://github.com/xisuo67/XHS-Spider/assets/148743326/9bee26ec-0d24-4b4a-b89e-e84458008f79)

### Details

在Win10环境下试用v1.0.2.1  尝试解析网页版笔记和个人主页均失败，附报错截图

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [X] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [ ] 我赞助了这个项目

**Comment by xisuo67** [comment]
补充链接
