### ISSUE TITLE
增加解析完成后，自动下载功能。

### ISSUE THREAD

**Issue by hxhxhx255** [xisuo67/XHS-Spider#123]
### Version

v1.0.2.2

### Platform

win10

### Steps to reproduce

增加新功能

### Details

软件全部解析之后，能够实现自动下载，这样既能提高解析的效率，又能提高下载的效率，另外再设置一个自动下载开关，由用户来选择全部解析之后，是否自动下载。

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [X] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [ ] 我赞助了这个项目

**Comment by xisuo67** [comment]
开发完成，2.3版本将集成该功能

**Comment by hxhxhx255** [comment]
好的，感谢大佬的完善，这个软件一定会开发的越来越完美，这个新功能版本大概什么时候发布呀，能不能先尝尝鲜呀？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月27日(周五) 晚上9:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xisuo67/XHS-Spider] 增加解析完成后，自动下载功能。 (Issue #123)




 
开发完成，2.3版本将集成该功能

**Comment by xisuo67** [comment]
不急，看本周能不能发吧！想等着导出功能开发完一起发

**Comment by hxhxhx255** [comment]
好的，感谢大佬辛苦付出，请教一下大佬，导出功能是指导出视频或者图片的真实下载地址嘛？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月27日(周五) 晚上9:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xisuo67/XHS-Spider] 增加解析完成后，自动下载功能。 (Issue #123)




 
不急，看本周能不能发吧！想等着导出功能开发完一起发

**Comment by xisuo67** [comment]
后面会写发布日志，看日志就行了
