### ISSUE TITLE
建议增加提取视频封面功能

### ISSUE THREAD

**Issue by hxhxhx255** [xisuo67/XHS-Spider#129]
### Version

v1.0.2.3

### Platform

win10

### Steps to reproduce

建议增加提取视频封面功能

### Details

建议增加提取视频封面功能

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [X] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [ ] 我赞助了这个项目

**Comment by xisuo67** [comment]
大哥们，你们提需求就提需求，为什么要提bug呢？

**Comment by CN-make** [comment]
> 大哥们，你们提需求就提需求，为什么要提bug呢？

maybe bug 你比較重視

**Comment by xisuo67** [comment]
> > 大哥们，你们提需求就提需求，为什么要提bug呢？
> 
> maybe bug 你比較重視

老登，皮一下就开心了？

**Comment by hxhxhx255** [comment]
大佬，建议增加文件重命名规则，例如文件命名可以为[更新日期]-[标题]-[序号]。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月29日(周日) 晚上9:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xisuo67/XHS-Spider] 建议增加提取视频封面功能 (Issue #129)




 
大哥们，你们提需求就提需求，为什么要提bug呢？
