### ISSUE TITLE
不能下载LIVE图

### ISSUE THREAD

**Issue by 8MbdSqLgsa** [xisuo67/XHS-Spider#134]
不能下载LIVE图

**Comment by xisuo67** [comment]
详细描述你的问题，否则将会关闭这个Issues

**Comment by 8MbdSqLgsa** [comment]
> 详细描述你的问题，否则将会关闭这个Issues

这种http://xhslink.com/wAnCmw苹果手机拍的LIVE照片，下载的是静态的图片不是动图

**Comment by xisuo67** [comment]
暂时不支持此类格式的批量下载
