### ISSUE TITLE
小程序登录界面卡死

### ISSUE THREAD

**Issue by hongsedaima** [xisuo67/XHS-Spider#146]
### Version

未知

### Platform

Android 14

### Steps to reproduce

![image](https://github.com/xisuo67/XHS-Spider/assets/37997806/23f61686-d5c4-46a4-bb45-71b74a9ac5d6)
登录按钮它就在那里，但它就是不让点，死活没反应。退出小程序重新进入，依然如此，无解。
实际上在注册的时候也出现过类似的情况，就是获取验证码的按钮无法点击，我退出小程序重新扫码打卡，注册完成了，但无法登录。

### Details

能正常登录

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [X] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [ ] 我赞助了这个项目

**Comment by xisuo67** [comment]
在微信里长按小程序图标，直到出现删除按钮后，将小程序删除，然后重新扫码尝试

**Comment by xisuo67** [comment]
已修复了这个问题
