### ISSUE TITLE
无法加入采集列表

### ISSUE THREAD

**Issue by fishergeehere** [xisuo67/XHS-Spider#149]
### Version

v1.0.3.6

### Platform

windows 11

### Steps to reproduce

其他都正常，选择后笔记无法加入采集列表。

### Details

其他都正常

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [X] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [ ] 我赞助了这个项目

**Comment by xisuo67** [comment]
自行更换授权
