### ISSUE TITLE
列名'ExtensionCount' 无效。

### ISSUE THREAD

**Issue by xzj-june** [xisuo67/XHS-Spider#153]
### Version

v1.0.4.3

### Platform

windows 10

### Steps to reproduce

登陆账户--登陆集成平台--看视频延期--进行采集--采集到一半闪退--重新打开软件并重复登录--采集--由于延期过了无法导出excel--看视频延期--导出excel提示(列名'ExtensionCount' 无效)--重新采集--闪退--再次登录后集成平台没有显示我的授权，也用不了采集、导出excel等功能了，点击就是提示登录集成平台，登录也是什么都没有。

### Details

账号登录后登录集成平台，没有显示我的授权
![2624cd06753a1055f8ef634d44de117](https://github.com/user-attachments/assets/931f2901-0e01-417a-b507-5d8d97ce8ed6)
点击新增提示限制申请，可是用不了啊，采集什么都要我重新授权
对了
最开始的问题是这个
![Uploading 6ff06a3bd5807e72d7ecf2197bdcd5c.png…]()
一天也就三个10分钟的延期，想用没法用...

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [X] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [ ] 我赞助了这个项目

**Comment by xzj-june** [comment]
![6ff06a3bd5807e72d7ecf2197bdcd5c](https://github.com/user-attachments/assets/d51f945f-c711-4263-bfd5-4e02ede9b9fb)
图片看不了重新发

**Comment by xisuo67** [comment]
授权网站升级未同步相应表结构，导致授权校验失败~
目前已解决这个问题
