### ISSUE TITLE
硬件信息与授权文件不匹配，已下载了.Net6但仍然没办法

### ISSUE THREAD

**Issue by unbie** [xisuo67/XHS-Spider#154]
### Version

v1.4.4.3

### Platform

windows11

### Steps to reproduce

小红书微信扫码登陆完后想解析笔记就会弹出重新扫码登陆，硬件信息与授权文件不匹配，尝试以往close的解决办法也没用

### Details

![image](https://github.com/user-attachments/assets/c6aa338f-5090-46db-9064-5cf487925b5b)

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [X] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [X] 我赞助了这个项目

**Comment by xisuo67** [comment]
一个授权文件绑定一台电脑硬件信息！更换其他电脑使用这个授权，会有对应的提示
