### ISSUE TITLE
作者您好。一次性只能解析201条笔记，弹窗显示“访问频次异常，请勿频繁操作或重启试试”

### ISSUE THREAD

**Issue by WC1265518477** [xisuo67/XHS-Spider#155]
### Version

v1.0.4.4

### Platform

Windows 11

### Steps to reproduce

解析完毕某博主第201条笔记后解析中断，弹窗显示“访问频次异常，请勿频繁操作或重启试试”，尝试重启软件后输入博主链接搜索结果为空，依然显示此异常弹窗。一小时后输入链接搜索恢复正常，但依然只能解析201条笔记之后重复上述步骤。解析速度设置为2s。

### Details

![微信图片_20240928232053](https://github.com/user-attachments/assets/fc60e30d-524f-4c19-a671-ec339a758692)

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [x] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [ ] 我赞助了这个项目

**Comment by xisuo67** [comment]
升级45版本

**Comment by I-BlueDragon** [comment]
> 升级45版本

可以请教一下如何解决吗？我更换代理ip后还是一样

**Comment by xisuo67** [comment]
> > 升级45版本
> 
> 可以请教一下如何解决吗？我更换代理ip后还是一样

下载最新的版本

**Comment by I-BlueDragon** [comment]
> > > 升级45版本
> > 
> > 
> > 可以请教一下如何解决吗？我更换代理ip后还是一样
> 
> 下载最新的版本

是否可以告知原理，我试着xs逆向访问xhs，最后卡在这里了

**Comment by txz521131** [comment]
无法解决，风控

**Comment by xisuo67** [comment]
> 无法解决，风控

风控这个问题一直没找到好的办法解决
