### ISSUE TITLE
笔记没有ip地址信息，其他爬取软件都有记录ip地址信息

### ISSUE THREAD

**Issue by 707806032** [xisuo67/XHS-Spider#156]
### Version

最新

### Platform

win11

### Steps to reproduce

可以加入记录笔记ip信息的功能

### Details

可以加入记录笔记ip信息的功能

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [X] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [X] 我赞助了这个项目

**Comment by xisuo67** [comment]
你需要在哪加ip？尽量不要一句话描述你的需求

**Comment by 707806032** [comment]
可以在每个笔记的文本里最底下回车写上。        ip地址：xxx



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月03日 22:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xisuo67/XHS-Spider] 笔记没有ip地址信息，其他爬取软件都有记录ip地址信息 (Issue #156) |

你需要在哪加ip？尽量不要一句话描述你的需求

**Comment by xisuo67** [comment]
没有理解~

**Comment by 707806032** [comment]
![Snipaste_2024-10-05_08-06-20](https://github.com/user-attachments/assets/999aa850-31c5-42fa-8e5c-cbd5ff66f97a)
就是ip地址信息在每个笔记文件夹里的文本文件里面的最底下

**Comment by 707806032** [comment]
当然，ip地址信息和上面的内容需要回车保存距离

**Comment by xisuo67** [comment]
你这个需求太个性化了一点，如果改动，可能会影响其他用户！导出笔记信息的时候，会有IP地址信息，暂时不考虑在文案后追加IP地址

**Comment by 707806032** [comment]
好的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月05日 19:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xisuo67/XHS-Spider] 笔记没有ip地址信息，其他爬取软件都有记录ip地址信息 (Issue #156) |

你这个需求太个性化了一点，如果改动，可能会影响其他用户！导出笔记信息的时候，会有IP地址信息，暂时不考虑在文案后追加IP地址

**Comment by Xw-Sjm** [comment]
作者您好~请问1.0.4.5版本导出笔记时没有IP这个字段啊？
