### ISSUE TITLE
下载安装程序提示有病毒

### ISSUE THREAD

**Issue by ChandlerKirby** [xisuo67/XHS-Spider#160]
### Version

v1.0.4.7

### Platform

Window 11

### Steps to reproduce

下载

### Details

![Image_20241129164813](https://github.com/user-attachments/assets/673c9c1a-12d3-4408-bcd9-08df08fa105e)

### Checklist

- [X] 我已经查看了现有问题以确保之前没有报告过此错误
- [X] 我已经为这个问题提供了一个描述性标题
- [X] 我已确保该错误可以在应用程序的最新版本上重现
- [X] 我已经提供了尽可能有效地重现此错误所需的所有信息
- [X] 我赞助了这个项目

**Comment by xisuo67** [comment]
陆续有人已经反馈了这个问题，我也在排查为什么会出现这种问题，还没有好的决绝方案，可能被哪个用户上报为病毒，导致一直提示。

**Comment by xisuo67** [comment]
你可以试试45版本

**Comment by ChandlerKirby** [comment]
已解决，谢谢
