### ISSUE TITLE
小红书x-s算法更新，提示浏览器异常，请尝试关闭/卸载风险插件或重启试试！

### ISSUE THREAD

**Issue by HaiLinWang** [xisuo67/XHS-Spider#25]

**Comment by xisuo67** [comment]
正在努力恢复中

**Comment by xisuo67** [comment]
@HaiLinWang 下载 v1.0.0.6版本，版本紧急恢复使用
- 更新功能
  - 更新x-s获取方式
  - 自动获取cookie
  - 移除设置cookie入口
  - 暂时不支持登录后的cookie设置
  - 待下个版本回复手动设置cookie
