### ISSUE TITLE
输入主页，只能采集10条内容，超出的不能采集

### ISSUE THREAD

**Issue by yanglr** [xisuo67/XHS-Spider#36]
输入主页，只能采集10条内容，超出的不能采集

版本号: v1.0.0.8

**Comment by xisuo67** [comment]
检测cookie是否有误，网页扫码登录后，从网页获取cookie，在系统设置后再试一遍

**Comment by yanglr** [comment]
感谢作者回复，重新填cookie确实可以了，谢谢
