### ISSUE TITLE
希望增加下载点赞帖子的功能

### ISSUE THREAD

**Issue by cor961** [xisuo67/XHS-Spider#49]
小红书上帖子质量良莠不齐，很少会有大部分帖子都值得保存的作者，更值得下载保存的往往是自己收藏或者点赞的帖子。

所以，希望增加登录后下载自己点赞的帖子的功能。

谢谢。

**Comment by xisuo67** [comment]
这个功能开发起来周期会比较长，需要单独增加页面，后面会纳入迭代计划，近期可能没太多时间做这一块的功能！感谢你的建议



&nbsp;

**Comment by xisuo67** [comment]
功能已开发完成，v1.0.1.2版本将发布该功能
