### ISSUE TITLE
你好大大，想问一下解析自己收藏专辑的话，只有十个。。有办法解决吗

### ISSUE THREAD

**Issue by l2581018** [xisuo67/XHS-Spider#60]
你好大大，想问一下解析自己收藏专辑的话，只有十个。。有办法解决吗
想着从收藏的参考样片专辑扒片子下来学习来着 0.o

**Comment by xisuo67** [comment]
你补充一下截图，对比网页版和我的系统数据，我看一下差异！这样描述太抽象，不知道问题出在哪里

**Comment by l2581018** [comment]
<img width="1588" alt="微信图片_20230616120417" src="https://github.com/xisuo67/XHS-Spider/assets/67934830/ad4a4287-b3e7-45d1-9ca7-11bcc74bb4fa">
但是现在，多几次似乎又能显示出来了

**Comment by xisuo67** [comment]
你把这个采集链接贴出来一下，我晚上抽空调试一下

**Comment by xisuo67** [comment]
如果没有其它问题的话，就先把这个问题关掉了。如果复现，重新打开这个问题
