### ISSUE TITLE
能不能新增web的搜索的数据呀。

### ISSUE THREAD

**Issue by chenjunqiang** [xisuo67/XHS-Spider#69]
能不能新增web的搜索的数据呀。

web搜索，输入关键词，返回的有默认排序，还有最热排序，还有最新排序。

分别三个数据的返回，可以搞吗？

**Comment by xisuo67** [comment]
可以搞，后面有时间再搞

**Comment by shenyuea** [comment]
大佬可以提供下思路吗，我也搞搞

**Comment by xisuo67** [comment]
> 大佬可以提供下思路吗，我也搞搞

这个位置我这几天尝试过，接口还没调通，你可以先自己研究一下，有时间多交流

**Comment by xisuo67** [comment]
目前搜索关键词接口一天限制60次，不再花精力增加该功能，短期内不考虑关键词搜索功能
