### ISSUE TITLE
关于XHS.Spider使用问题

### ISSUE THREAD

**Issue by xisuo67** [xisuo67/XHS-Spider#72]
- 程序闪退
  -  检查是否安装.net 6.0运行时
  -  程序启动后闪退，检查是否安装webview2运行时
- 关于采集数据只有10条问题
  - 大哥们，你们能扫码登录嘛？天天问，我也很无奈啊！文档不看，录的操作视频也不看，我不是客服不要疯狂@作者

**Comment by easyphoto** [comment]
申请退款，开通订阅服务，支付9.9元，小程序里没有找到签到按钮，APP上授权管理无法使用。我的支付宝id 18631101260
