### ISSUE TITLE
在登陆的情况下，能不能导入一批笔记详情页的链接，然后慢慢下载下来？

### ISSUE THREAD

**Issue by chenjunqiang** [xisuo67/XHS-Spider#77]
在登陆的情况下，能不能导入一批笔记详情页的链接，然后慢慢下载下来？

慢慢的阈值可以设置。

下载下来需要 素材 + 笔记 + 点赞数 + 收藏数 + 评论数。

这几个。

**Comment by xisuo67** [comment]
可以考虑，不过最近在搞另外一个项目，后面考虑加入迭代

**Comment by xisuo67** [comment]
2.3版本发布这个功能
