### ISSUE TITLE
下载图片损坏或者图片缺失

### ISSUE THREAD

**Issue by lordaeron4to** [xisuo67/XHS-Spider#82]
会出现有的图片只有一半，或者有的图片没有下载
![2](https://github.com/xisuo67/XHS-Spider/assets/32866787/784d9b6d-5ad1-452b-a08f-52df727aee24)

**Comment by xisuo67** [comment]
这种需要进一步确认，下载不完全分两种情况:
1.程序正在下载，尚未下载完成，点开图片，导致图片加载有误
2.程序bug
确认两者不同之处在于，程序下载完会有提示信息，如果出现提示信息，而图片出现加载一半情况为bug
由于提供信息无法判断是哪种情况，请添加补充信息后，再安排排查

**Comment by lordaeron4to** [comment]
> 

开启了提示，提示下载完成后出现的图片损坏情况
