### ISSUE TITLE
1.0.1.4版本，在使用中发现的4个问题和建议

### ISSUE THREAD

**Issue by 675535** [xisuo67/XHS-Spider#92]
先说下，软件非常好，感谢作者的辛苦付出！！以下是使用中发现的3个问题：

1.如果先搜索到了内容，再切换为“设置页”，然后切换回“搜索页”，内容没有了，还是让搜索；
2.搜索结果，无法全选，点击全选时，只”反选“了当前能看到的笔记，并且全选的勾勾状态不正确；
3.扫描结果缺失，最后几篇笔记并未显示出来；
4.下拉界面扩大时，列表中最多显示9条笔记，下方为空白区域。

以下是一点点小建议：
1.增加笔记总数显示，现在已解析数量知道，但是并不知道解析到什么位置了；
2.增加边解析边下载功能，即解析后自动下载；
3.增加点击下载已选项时，如笔记未解析，则自动解析，并且在解析后自动下载；
4.在页面最下边增加一条状态栏，以显示下载进度、提示或者错误等信息，目前提示是使用WINDOWS弹窗提示的；
5.在能保证账号安全或者服务器允许的情况下，增加多线程下载，适当提高下载速度。

**Comment by 675535** [comment]
更正下第3点：
3.扫描结果缺失，最后几篇笔记并未显示出来；

经测试，实际情况为：
1.下拉列表拉下边部分被窗体遮挡，以至于看不到最后3篇笔记，必须将窗体下边缘向下拉到最大，才能看到最后3篇笔记；
2.被下载博主的倒数第2篇笔记未显示出来，就是说，实际缺少1篇笔记未能扫描到。

**Comment by xisuo67** [comment]
感谢你的使用建议，我会验证后认真回复你的每一条反馈！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月9日(周日) 上午7:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xisuo67/XHS-Spider] 1.0.1.4版本，在使用中发现的4个问题和建议 (Issue #92)




 
先说下，软件非常好，感谢作者的辛苦付出！！以下是使用中发现的3个问题：
 
1.如果先搜索到了内容，再切换为“设置页”，然后切换回“搜索页”，内容没有了，还是让搜索；
 2.搜索结果，无法全选，点击全选时，只”反选“了当前能看到的笔记，并且全选的勾勾状态不正确；
 3.扫描结果缺失，最后几篇笔记并未显示出来；
 4.下拉界面扩大时，列表中最多显示9条笔记，下方为空白区域。
 
以下是一点点小建议：
 1.增加笔记总数显示，现在已解析数量知道，但是并不知道解析到什么位置了；
 2.增加边解析边下载功能，即解析后自动下载；
 3.增加点击下载已选项时，如笔记未解析，则自动解析，并且在解析后自动下载；
 4.在页面最下边增加一条状态栏，以显示下载进度、提示或者错误等信息，目前提示是使用WINDOWS弹窗提示的；
 5.在能保证账号安全或者服务器允许的情况下，增加多线程下载，适当提高下载速度。

**Comment by xisuo67** [comment]
> 更正下第3点： 3. 扫描结果失败，最后几篇报告显示出来；
> 
> 经过测试，实际情况为： 1.下拉列表拉下边部分被单张，足够看不到最后3篇笔记，必须将单张下边缘向下拉到最大，才能看到最后3篇笔记； 2.被 下载博主的倒数第2篇笔记未显示出来，就是说，实际缺少第1篇笔记未能扫描到。后来经过我仔细对比，已经确认，这篇笔记只能在APP端看到，电脑网页端的主页表格中显示此篇笔记，如果直接访问这篇笔记的地址，则显示“当前内容无法显示”。

关于提到的**实际缺少第1篇笔记未能扫描到**问题，这里回复一下，由于调用小红书web端api，如果发现数据缺失情况，首先检查web端，博主笔记是否异常，所有数据均从web端的api返回，如果XHS.Spider数据采集笔记缺失，大部分原因是因为笔记异常导致。

**Comment by xisuo67** [comment]
> 下拉界面扩大时，列表中最多显示9条笔记，下方为空白区域

首先回复使用中的问题：
关于第一点：XHS.Spider切换导航栏时，确实需要重新采集数据，这一点我认为不应该认定为bug。关于这一点需要特别解释，XHS.Spider从4月25日开源至今，初创时仅仅是一个控制台程序，而它也仅仅是为了满足个人下载需求，程序从设计之初就没考虑做数据持久化，所有采集数据均在内存操作与释放，只是没想到开源后会引起这么多朋友关注！随着用户群体增多，在修复bug同时还要满足各种需求，作者本人实在精力有限，未来暂时也没考虑实现你提的第一点需求，这里还望见谅。
关于第二点：这里我还没来得及验证，如果确实如你所说，下个版本将会修复这里的bug
第三点：已回复，不再重复回复
第四点：**下拉界面扩大时，列表中最多显示9条笔记，下方为空白区域。**这里应该是当初开发时界面设计不合理，导致数据展示不全，下个版本也将修复这个问题，非常感谢你提的这几点问题。

关于程序增强建议的回复：
前面四点均围绕自动解析并下载的增强意见，这里也需要做个解释，小红书反爬越来越严，目前手动解析尚且时间久了会触发反爬，导致api暂时无法调用成功，更何况自动解析，再开发、测试过程中已验证自动解析的不可行，通常触发反爬后，api会间隔3-5分钟无法调通，并不是不想智能化，属实限制太多……

关于第五点：这里要特别说明，为什么单线程下载？作者认为，随着用户体量提升，多线程暴力数据采集，近乎DNS攻击，目前软件下载量已有4.3K，随着XHS.Spider被更多用户推广，作者有理由相信，不久的将来下载体量会远远大于这个数字，若不加以控制，无论如何**保证账号安全或者服务器允许的情况下，增加多线程下载，适当提高下载速度**，未来对小红书服务器造成的压力都是无法估量的，如若对小红书服务器造成宕机，作者恐怕就没有机会在这里回复你的Issues了。并且XHS.Spider更多倾向于学习交流，所以多线程好加，但无论什么时候，都不考虑增加多线程下载，也请理解……

**Comment by xisuo67** [comment]
从软件易用性来说，你提出的建议都非常的棒，但是从实际出发，作者在开发项目时，必须有所限制！

**Comment by 675535** [comment]
> 

仔细看完作者这么认真的回复，也完全理解了您的意思，其实除了全选问题比较影响操作外，其它都不是必要的。
希望作者空余时，麻烦解决下 全选/反选 问题，和稍微处理下那个列表显示不全的问题，辛苦了 ^-^

**Comment by xisuo67** [comment]
> 空余

这个问题已经在1.5版本解决

**Comment by xisuo67** [comment]
> > 笔记只能在APP端看到，电脑网页端的主页中并未显示此篇笔记，如果直接访问这篇笔记的地址，则显示”当前内容无法展示“
> 
> 我也遇到了第二个问题，笔记只能在APP端看到，电脑网页端的主页中并未显示此篇笔记，如果直接访问这篇笔记的地址，则显示”当前内容无法展示“，这个有没办法解决

低版本不再维护，建议升级至高版本，通过你描述的情况，这条笔记多半已违规
