### ISSUE TITLE
大佬我知道開源項目被到源碼被改UI是一件令人作嘔的事情

### ISSUE THREAD

**Issue by CN-make** [xisuo67/XHS-Spider#94]
我也下載了v1.015版本，這個調取授權對普通的用戶還會處理嗎，還是僅用於一些有過資助的人開放。我的建議是反正都要賺元子。作者也可以爲什麽不自己把這個元子賺了

**Comment by xisuo67** [comment]
目前授权对所有人开放的，没考虑盈利，先把软件做好再说！

**Comment by xisuo67** [comment]
[XHS.Spider官网](https://xisuo67.website/XHS-Spider-Doc/backend/illustrate.html)也阐述了闭源的前因后果，授权对所有用户开放，暂时不考虑盈利

**Comment by CN-make** [comment]
> [XHS.Spider官网](https://xisuo67.website/XHS-Spider-Doc/backend/illustrate.html)也阐述了闭源的前因后果，授权对所有用户开放，暂时不考虑盈利

我欠某播一個會員 也欠你一個

**Comment by xisuo67** [comment]
> > [XHS.Spider官网](https://xisuo67.website/XHS-Spider-Doc/backend/illustrate.html)也阐述了闭源的前因后果，授权对所有用户开放，暂时不考虑盈利
> 
> 我欠某播一個會員 也欠你一個

感谢理解，闭源也下了很大决心，随着XHS.Spider快速迭代，实在不想让自己心血被人盗用，只能出此下策。

**Comment by CN-make** [comment]
> > > [XHS.Spider官网](https://xisuo67.website/XHS-Spider-Doc/backend/illustrate.html)也阐述了闭源的前因后果，授权对所有用户开放，暂时不考虑盈利
> > 
> > 
> > 我欠某播一個會員 也欠你一個
> 
> 感谢理解，闭源也下了很大决心，随着XHS.Spider快速迭代，实在不想让自己心血被人盗用，只能出此下策。

我已經獲取授權 但是軟體檢測我還是未獲取授權，是要和安裝路徑一致？

**Comment by xisuo67** [comment]
是的，授权文件与你exe目录一致就可以了

**Comment by xisuo67** [comment]
不是的，应该是改出来的bug，内存占用率太高，下个版本把它修复掉

**Comment by xisuo67** [comment]
> ![image](https://user-images.githubusercontent.com/135316273/261358841-90061e3c-a26a-43d8-9954-418d5aa3db47.png) 請問是我的硬件問題嗎？ 解析會一直導致無響應

v1.0.1.7版本已修复内存占用率居高不下问题
