### ISSUE TITLE
I just banned from xiaohongshu after using XHS-Spider-v1.0.1.3

### ISSUE THREAD

**Issue by misabear14** [xisuo67/XHS-Spider#97]
![Screenshot_20230826-023309](https://github.com/xisuo67/XHS-Spider/assets/143222842/ee484fa2-6118-45d2-ad22-d0706ccedcee)

![ShareX_fzK5Ijmdt0](https://github.com/xisuo67/XHS-Spider/assets/143222842/bf520974-cd77-4136-873e-da75d022aa17)

A few days ago, I used the new version 1.6, but when analyzing the link, the application stopped working and quit, so I used the 1.3 version that I found the most stable. All images downloaded to me are only saved in my computer, and are not used for any commercial purposes.

Recently I have used XHS-Spider-v1.0.1.3 to download images on xiaohongshu, I have logged in on my phone and chrome. Every time I use it, I have to scan the QR code, and the account on the website will be log out.

Tonight after downloading pictures from an account, I got banned on the phone app. I don't know Chinese so I'm quite confused, and I don't know if I can get my account back or not? 
So people should be careful when using it. I'm so sad right now.

**Comment by xisuo67** [comment]
I'm so sorry,
xiaohongshu has a strict anti-pickpocketing mechanism,Large numbers of acquisitions can result in bans.
I made it clear in the issues that collecting data would lead to banning, but I didn't consider foreign users.

![image](https://github.com/xisuo67/XHS-Spider/assets/22284363/15d3e1c6-ac8e-4a99-bcef-1070e1d3b140)

**Comment by misabear14** [comment]
Thank you for the response, I used google translate to read some tutorials but I didn't pay attention to this warning. Anyway thank you for making this useful software for everyone.

**Comment by xisuo67** [comment]
Thank you for your support and good luck

**Comment by xisuo67** [comment]
In version 1.6, a bug where the application unexpectedly stopped working and caused the program to quit while analyzing links was fixed in version 1.7

**Comment by hyning951499752** [comment]
能否增加一个主页点赞数量排序的功能,博主有几百个视频,我只想选出中间点赞数量优质的视频下载

**Comment by hyning951499752** [comment]
降序的就可以了谢谢
