### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Zxuuuuu** [xisuo67/XHS-Spider#99]
给孩子加个进度条或者任务完成情况吧。

具体是批量采集作品->批量下载->跳转到其他页面，下载任务还在后台运行，但总体下载进度就不见了，只能眼睁睁的看着系统一个一个的冒提示，前两天下了一个作者的1000+作品，提示提的烦死了还不敢关，不知道什么时候结束。

建议看看能不能搞个后台下载任务的进度条啥的，显示当前下载任务队列，和下载信息。

**Comment by xisuo67** [comment]
暂时没考虑加下载任务，因为考虑做其他采集工具，每个工具都维护下载界面太麻烦，也没什么精力维护！后面考虑单独做一个类似迅雷的下载程序，数据采集工具只做采集的事情，具体下载工作交给下载工具就行了
